<a href="https://colab.research.google.com/github/sanyagupta31/LLM-based-clone/blob/main/knn_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from collections import Counter
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
cmap = ListedColormap(['#FF0000', '#00FF00', '#0000FF'])


In [ ]:
df = pd.read_csv("/content/gender_submission.csv")
attributes = df.columns.tolist()
print(attributes)
feature_names = attributes[0:2]
print(feature_names)
if len(attributes) > 2:
  target_name = attributes[2]
  print(target_name)
else:
 print( "The dataframe has fewer than 3 columns, so 'target_name' cannot")



['PassengerId', 'Survived']
['PassengerId', 'Survived']
The dataframe has fewer than 3 columns, so 'target_name' cannot


In [ ]:
target_name = attributes[1]
print(target_name)

Survived


In [ ]:
df.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [ ]:
df.describe()

PassengerId    Survived
count   418.000000  418.000000
mean   1100.500000    0.363636
std     120.810458    0.481622
min     892.000000    0.000000
25%     996.250000    0.000000
50%    1100.500000    0.000000
75%    1204.750000    1.000000
max    1309.000000    1.000000

In [ ]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
print(X_train)

[[ 912]
 [1198]
 [1034]
 [ 906]
 [1176]
 [ 994]
 [1160]
 [1005]
 [ 967]
 [ 956]
 [ 947]
 [1142]
 [1242]
 [1138]
 [1046]
 [1137]
 [1282]
 [1166]
 [1109]
 [1289]
 [1217]
 [1100]
 [ 948]
 [ 900]
 [1207]
 [1047]
 [1050]
 [1168]
 [1299]
 [1049]
 [ 998]
 [1155]
 [ 955]
 [1187]
 [1060]
 [1190]
 [1249]
 [ 973]
 [ 999]
 [1258]
 [1306]
 [1189]
 [ 988]
 [1273]
 [ 981]
 [1125]
 [1083]
 [1246]
 [1145]
 [ 984]
 [1132]
 [1086]
 [1274]
 [1051]
 [1098]
 [ 958]
 [1223]
 [1067]
 [1032]
 [ 993]
 [1219]
 [1097]
 [1235]
 [ 909]
 [1038]
 [1063]
 [1110]
 [ 922]
 [1006]
 [1245]
 [ 995]
 [1088]
 [1151]
 [1218]
 [1008]
 [1239]
 [1012]
 [1303]
 [1004]
 [1124]
 [1028]
 [1257]
 [1018]
 [1092]
 [1292]
 [1188]
 [1025]
 [ 925]
 [1287]
 [1054]
 [ 926]
 [1121]
 [ 989]
 [ 977]
 [ 953]
 [1059]
 [1065]
 [1199]
 [1300]
 [1301]
 [1139]
 [1123]
 [1000]
 [1212]
 [ 938]
 [1286]
 [1234]
 [1133]
 [ 965]
 [1029]
 [1290]
 [1113]
 [1117]
 [ 921]
 [1073]
 [1195]
 [1272]
 [ 943]
 [1237]
 [1261]
 [ 919]
 [ 894]
 [1126]
 [1048]
 [1210]


In [ ]:
print(y_train)

[0 0 0 1 1 0 1 1 0 0 0 1 1 1 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 0 0
 0 0 0 1 0 1 0 0 0 0 1 0 1 1 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1
 0 1 1 1 1 0 0 1 0 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0
 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0
 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 1 0 1 0 0 0 0 0 1 1 1 1 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 0 0
 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 0 1 1 1 1 1 0 0 1 0 0 0 0 0 1 0 1 1 1
 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 1 1 0 1 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0
 0]


In [ ]:
print(X_test)

[[1252]
 [1062]
 [1116]
 [1250]
 [1201]
 [1200]
 [1042]
 [ 902]
 [ 913]
 [1153]
 [1241]
 [ 951]
 [1298]
 [1090]
 [1244]
 [ 968]
 [1268]
 [1056]
 [ 904]
 [1080]
 [1238]
 [ 929]
 [1276]
 [ 946]
 [1037]
 [1179]
 [1091]
 [1146]
 [1270]
 [1202]
 [1267]
 [1131]
 [ 982]
 [ 907]
 [1302]
 [1231]
 [1194]
 [1033]
 [ 966]
 [1141]
 [1253]
 [ 970]
 [1174]
 [1259]
 [1193]
 [1045]
 [1111]
 [1280]
 [ 952]
 [1221]
 [1309]
 [ 898]
 [ 893]
 [1204]
 [1036]
 [1164]
 [1163]
 [1024]
 [1127]
 [1178]
 [1082]
 [ 957]
 [1071]
 [1016]
 [1026]
 [1078]
 [ 941]
 [ 944]
 [ 918]
 [ 937]
 [1027]
 [ 896]
 [1112]
 [1263]
 [1014]
 [1122]
 [ 897]
 [1068]
 [1203]
 [ 992]
 [ 899]
 [ 914]
 [ 960]
 [1220]]


In [ ]:
print(y_test)

[0 0 1 0 1 0 1 0 0 0 1 1 0 0 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0
 1 1 1 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 0 1 1 1 1 0 0 1 1 1
 1 0 0 1 0 1 0 1 0 0]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-1.60716893e+00]
 [ 8.01756158e-01]
 [-5.79585499e-01]
 [-1.65770582e+00]
 [ 6.16454228e-01]
 [-9.16498099e-01]
 [ 4.81689189e-01]
 [-8.23847134e-01]
 [-1.14391410e+00]
 [-1.23656507e+00]
 [-1.31237040e+00]
 [ 3.30078519e-01]
 [ 1.17236002e+00]
 [ 2.96387259e-01]
 [-4.78511719e-01]
 [ 2.87964444e-01]
 [ 1.50927262e+00]
 [ 5.32226078e-01]
 [ 5.21256245e-02]
 [ 1.56823232e+00]
 [ 9.61789643e-01]
 [-2.36797104e-02]
 [-1.30394759e+00]
 [-1.70824271e+00]
 [ 8.77561493e-01]
 [-4.70088904e-01]
 [-4.44820460e-01]
 [ 5.49071708e-01]
 [ 1.65246047e+00]
 [-4.53243274e-01]
 [-8.82806839e-01]
 [ 4.39575114e-01]
 [-1.24498788e+00]
 [ 7.09105193e-01]
 [-3.60592310e-01]
 [ 7.34373638e-01]
 [ 1.23131972e+00]
 [-1.09337721e+00]
 [-8.74384024e-01]
 [ 1.30712506e+00]
 [ 1.71142018e+00]
 [ 7.25950823e-01]
 [-9.67034988e-01]
 [ 1.43346728e+00]
 [-1.02599469e+00]
 [ 1.86890664e-01]
 [-1.66867565e-01]
 [ 1.20605128e+00]
 [ 3.55346964e-01]
 [-1.00072625e+00]
 [ 2.45850369e-01]
 [-1.41599120e-01]
 [ 1.4418901

In [ ]:
print(X_test.dtype)

float64


In [ ]:
def euclidean_distance(x1, x2):
    distance = np.sqrt(np.sum((x1-x2)**2))
    return distance

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def predict(self, X):
        predictions = [self._predict(x) for x in X]
        return predictions

    def _predict(self, x):
        # compute the distance
        distances = [euclidean_distance(x, x_train) for x_train in self.X_train]

        # get the closest k
        k_indices = np.argsort(distances)[:self.k]
        k_nearest_labels = [self.y_train[i] for i in k_indices]

        # majority vote
        most_common = Counter(k_nearest_labels).most_common()
        return most_common[0][0]

In [ ]:
clf = KNN(k=5)
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)

print(predictions)

acc = np.sum(predictions == y_test) / len(y_test)
print(acc)


[1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0]
0.4880952380952381


In [ ]:
import pandas as pd

# Load training data
train_data = pd.read_csv('train.csv')

# Load test data
test_data = pd.read_csv('test.csv')


In [ ]:
# Example preprocessing for training data
train_data['Age'].fillna(train_data['Age'].median(), inplace=True)
train_data['Sex'] = train_data['Sex'].map({'male': 0, 'female': 1})
train_data['FamilySize'] = train_data['SibSp'] + train_data['Parch'] + 1

# Prepare features and target variable
X_train = train_data[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'FamilySize']]
y_train = train_data['Survived']


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# Initialize and train the model
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train, y_train)


KNeighborsClassifier()

In [ ]:
# Example preprocessing for test data
test_data['Age'].fillna(test_data['Age'].median(), inplace=True)
test_data['Sex'] = test_data['Sex'].map({'male': 0, 'female': 1})
test_data['FamilySize'] = test_data['SibSp'] + test_data['Parch'] + 1

# Prepare features for prediction
X_test = test_data[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'FamilySize']]


In [ ]:
test_predictions = clf.predict(X_test)


In [ ]:
submission = pd.DataFrame({
    'PassengerId': test_data['PassengerId'],  # From your test data
    'Survived': test_predictions                # Your predictions
})


In [ ]:
submission.to_csv('knn_submission.csv', index=False)  # Save to CSV
print("Submission file created!")


Submission file created!


In [ ]:
from google.colab import files
files.download('knn_submission.csv')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>